version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'node_modules/**/*'

env:
  variables:
    NODE_ENV: "production"
    SERVERLESS_ACCESS_TOKEN: "AKpzzi6aflNjvWcpDGjxRvyxyyTq1hz8v5OBCt13ubusf"  # Get from Serverless Dashboard
    AWS_REGION: "us-east-1"  # Set your preferred region

phases:
  install:
    runtime-versions:
      python: 3.9          # Use your Python version
      nodejs: 18           # Use an LTS version like Node.js 18
    commands:
      - echo Installing Python dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo Installing Node.js dependencies...
      - npm install -g serverless@4.3.2
      - npm install

  pre_build:
    commands:
      - echo "Verifying installations..."
      - node --version
      - python --version
      - sls --version
      - echo "Running tests..."
      - pytest tests/ || echo "Tests completed"

  build:
    commands:
      - echo "Packaging application..."
      - sls package --stage dev

  post_build:
    commands:
      - echo "Deploying to AWS..."
      - sls deploy --stage dev --verbose

artifacts:
  files:
    - '**/*'
  discard-paths: yes