service: cta-dashboard

provider:
  name: aws
  runtime: python3.9  # or whichever Python version you use
  region: us-east-1   # pick your region
  stage: dev

functions:
  app:
    handler: wsgi_handler.handler
    # Map all HTTP methods and paths to your Flask app:
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app  # 'app' is your filename (app.py), 'app' is the Flask instance
  pythonRequirements:
    dockerizePip: true

# (Optional) environment variables for your CTA keys:
#   provider:
#     environment:
#       BUS_API_KEY: "xxxxx"
#       TRAIN_API_KEY: "yyyyy"